### ISSUE TITLE
Info domain에 인물 정보 삭제 API 추가

### ISSUE THREAD

**Issue by hou27** [GUESS-ME-GDSC/Server#16]
# Info
논의를 통해 인물의 정보를 삭제하는 api를 따로 두기로 결정하여 작업 진행
[인물 정보 삭제 API 명세서](https://www.notion.so/id-eb5443281658450d8e94b50d29b20dbc?pvs=4)

[figma에서의 협의 내용](https://www.figma.com/file/RF79B4yiaB731x1d4uzhNW?node-id=53:417#396590242)

| Method                         | URL | Usage                |
| --------------------------- | ------ | -------------------- |
|DELETE | /	| 정보 삭제|

**Comment by hou27** [comment]
[정보 삭제 api](https://www.notion.so/id-eb5443281658450d8e94b50d29b20dbc?pvs=4)
@915dbfl 이렇게 설계했는데 협의한 내용대로인지 확인 부탁해요

**Comment by 915dbfl** [comment]
@hou27 확인했습니다! info가 key, value 묶음 리스트일까요?

**Comment by hou27** [comment]
@915dbfl 예시는 다음과 같습니다. 작성한 데이터의 의미는 무시해주세요

```json
{
    "info": [
        {
            "infoKey": "마우스",
            "infoValue": "핸드폰"
        },
        {
            "infoKey": "안경",
            "infoValue": "렌즈"
        }
    ]
}
```

말씀드린 순간 id만 넘겨받으면 된다는 걸 깨달았습니다.

```json
{
    "info": [
        1,
        2
    ]
}
```

**Comment by 915dbfl** [comment]
@hou27 맞네요! 확인했습니다!

**Comment by hou27** [comment]
> @hou27 맞네요! 확인했습니다!

api url도 수정했습니다

| Method                         | URL | Usage                |
| --------------------------- | ------ | -------------------- |
|DELETE | /	| 정보 삭제|

**Comment by hou27** [comment]
@915dbfl 이렇게 변경해도 될까요?
```json
{
    "idList": [
        1,
        2
    ]
}
```
