### ISSUE TITLE
채점 메소드에서 이미지 처리 방법

### ISSUE THREAD

**Issue by bluesun147** [GUESS-ME-GDSC/Server#19]
채점 시 클라이언트에서 넘겨주는 이미지 어떻게 처리할 지

- 클라우드에 한번 올리고 텍스트 추출
- 현재 예시 방법처럼 filePath 안드로이드에서 바로 사용할 수 있는지 찾아보기

**Comment by hou27** [comment]
넘어오는 이미지 파일은 바로 api에 못 싣는 건가요?

**Comment by bluesun147** [comment]
> 넘어오는 이미지 파일은 바로 api에 못 싣는 건가요?

그게 지금은 filepath 넣어주면 바로 넣을 수 있는데 안드로이드에서도 가능한지 모르겠어서 찾아보는 중
만약 안되면 클라우드에 올리고 그거 다시 받아서 쓰면 될거 같아요
