### ISSUE TITLE
GCP 배포

### ISSUE THREAD

**Issue by bluesun147** [GUESS-ME-GDSC/Server#21]
CI/CD 어떤식으로 할 지

<참고>
- [Jenkins] GCP + Docker + Jenkins를 이용한 CI / CD : https://dev-gorany.tistory.com/345
- cloud run : https://kimtaehyun98.tistory.com/154
- https://velog.io/@roo333/GCP로-CICD-구축-후기

**Comment by hou27** [comment]
github action 밖에 안 써봤어서 좋은 듯!

[Spring, Docker ,Jenkins, Nginx를 사용한 무중단 배포 (GCP 인스턴스 배포 , docker 설치)](https://velog.io/@suker80/Spring-Docker-Jenkins-Nginx%EB%A5%BC-%EC%82%AC%EC%9A%A9%ED%95%9C-%EB%AC%B4%EC%A4%91%EB%8B%A8-%EB%B0%B0%ED%8F%AC)

**Comment by hou27** [comment]
# GCP 배포 환경에서의 문제 해결

GCP로 배포하면 GOOGLE_APPLICATION_CREDENTIALS 관련 에러가 발생하는 탓에
GCP API 가 동작하지 못했었던 이슈가 있었는데,

로컬에서 dockerfile을 빌드할 때 
로컬의 gcp json key를 복사해간 후 해당 경로로 환경변수를 설정하여 문제를 해결함.

### Dockerfile

```dockerfile
FROM openjdk:11
ENV GOOGLE_APPLICATION_CREDENTIALS=./involuted-span-377818-befce0f2e2e3.json
ARG JAR_FILE=./build/libs/guessme-0.0.1-SNAPSHOT.jar
COPY ${JAR_FILE} app.jar
COPY ./src/main/resources/involuted-span-377818-befce0f2e2e3.json ./
# env
ENTRYPOINT ["java","-jar","/app.jar"]
```
