### ISSUE TITLE
Person 관련 작업

### ISSUE THREAD

**Issue by hou27** [GUESS-ME-GDSC/Server#3]
# Person

> 인물 도메인에 해당하는 Controller, Service를 작업하고자 한다.

| Method                         | URL | Usage                |
| --------------------------- | ------ | -------------------- |
|GET	|/all/{favorite=true}	|즐겨찾기 또는 아닌 인물들 조회|
|POST	|/	|인물 추가|
|GET|	/{id}	|인물 상세 조회|
|PATCH|	/{id}	|인물 정보 수정|
|DELETE	|/{id}	|인물 삭제|
|PATCH|	/{id}/favorite	|인물 즐겨찾기 설정|
|POST |/{id}/newinfo	|인물 정보 추가|

**Comment by hou27** [comment]
@bluesun147 우리 이름같은 인물 필수 정보를 인물 테이블로 옮긴 만큼
https://www.notion.so/5997ca5c1e6d4262bc9963a639fff9ac?pvs=4 
여기 request body에 이름, 생년월일 같은 건 따로 담고 추가 정보를 info 리스트에 남아서 넘기도록 바꾸는 건 어때?

```json
{
    "image": "asdimage",
    "voice": "asdvoice",
    "name": "김민수",
    "relation": "친구",
    "birth": "2023-01-18T11:22:33",
    "residence": "서울",
    "info": [
        {
            "infoKey": "직업",
            "infoValue": "도인"
        },
        {
            "infoKey": "hobby",
            "infoValue": "축구"
        }
    ]
}
```

이런 식으로 들어오도록

@bluesun147 구조 수정되었습니다

**Comment by bluesun147** [comment]
> @bluesun147 우리 이름같은 인물 필수 정보를 인물 테이블로 옮긴 만큼 https://www.notion.so/5997ca5c1e6d4262bc9963a639fff9ac?pvs=4 여기 request body에 이름, 생년월일 같은 건 따로 담고 추가 정보를 info 리스트에 남아서 넘기도록 바꾸는 건 어때?
> 
> ```json
> {
>     "image": ???,
>     "voice": ???,
>     "name": "김민수",
>     "relation": "친구",
>     "birth": "1999-01-01",
>     "residence": "서울",
>     "info": {
>         "hobby": "게임",
>         "직업": "도인"
>     }
> }
> ```
> 
> 이런 식으로 들어오도록

굿 아이디어

**Comment by hou27** [comment]
```java
@Column(columnDefinition = "bigint default 0")
```
위 코드론 application 단에서 데이터 삽입 시 default 값이 적용되지 않음
