### ISSUE TITLE
DB 연결

### ISSUE THREAD

**Issue by hou27** [GUESS-ME-GDSC/Server#4]
# DB 연결

MYSQL 연결 (develop branch에서 작업함)

**Comment by hou27** [comment]
1. Character, Info Entity에 누락된 애노테이션 추가
2. [MYSQL 예약어](https://henerd.tistory.com/24) 아티클을 참고하여 ddl 쿼리 실행 시 발생하던 에러 해결

**Comment by hou27** [comment]
@bluesun147 수정사항있는데 작업 끝내기 전에 새로 네이밍한 부분 피드백받고 닫을게
## 예약어 관련 오류로 변경된 부분
- Character -> Person
- like -> favorite
- key -> infoKey
- value -> infoValue

**Comment by bluesun147** [comment]
> @bluesun147 수정사항있는데 작업 끝내기 전에 새로 네이밍한 부분 피드백받고 닫을게
> 
> ## 예약어 관련 오류로 변경된 부분
> * Character -> Person
> * like -> favorite
> * key -> infoKey
> * value -> infoValue

이렇게 합시다, 예약어 이렇게 많은 줄 몰랐네
erd는 내가 수정해둘게

**Comment by hou27** [comment]
# 현재 생성된 테이블 모습
mysql> show tables;

| Tables_in_guessme |
|-------------------|
| info              |
| person            |
| user              |
3 rows in set (0.04 sec)

mysql> desc user;
| Field         | Type         | Null | Key | Default | Extra |
|---------------|--------------|------|-----|---------|-------|
| id            | binary(16)   | NO   | PRI | NULL    |       |
| user_id       | varchar(255) | NO   | UNI | NULL    |       |
| user_password | varchar(255) | NO   |     | NULL    |       |

3 rows in set (0.04 sec)

mysql> desc info;
| Field      | Type         | Null | Key | Default | Extra |
|------------|--------------|------|-----|---------|-------|
| id         | binary(16)   | NO   | PRI | NULL    |       |
| created_at | datetime(6)  | NO   |     | NULL    |       |
| info_key   | varchar(255) | NO   |     | NULL    |       |
| info_value | varchar(255) | NO   |     | NULL    |       |
| person_id  | binary(16)   | YES  | MUL | NULL    |       |

5 rows in set (0.04 sec)

mysql> desc person;
| Field     | Type         | Null | Key | Default | Extra |
|-----------|--------------|------|-----|---------|-------|
| id        | binary(16)   | NO   | PRI | NULL    |       |
| birth     | date         | NO   |     | NULL    |       |
| favorite  | bit(1)       | YES  |     | b'0'    |       |
| image     | varchar(255) | NO   |     | NULL    |       |
| name      | varchar(255) | NO   |     | NULL    |       |
| relation  | varchar(255) | NO   |     | NULL    |       |
| residence | varchar(255) | NO   |     | NULL    |       |
| score     | bigint       | YES  |     | NULL    |       |
| voice     | varchar(255) | YES  |     | NULL    |       |
| user_id   | binary(16)   | YES  | MUL | NULL    |       |

10 rows in set (0.04 sec)

**Comment by hou27** [comment]
@bluesun147 그럼 내가 기능명세서 수정할게
